repos:
  - repo: https://github.com/psf/black
    rev: 24.2.0  # Use the appropriate version
    hooks:
      - id: black
  - repo: https://github.com/pycqa/flake8
    rev: 6.1.0   # Use the appropriate version
    hooks:
      - id: flake8