# .github/workflows/python-test.yml
name: Python Tests

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: ["3.9", "3.10", "3.11"] # Specify Python versions to test against

    steps:
    - uses: actions/checkout@v3

    - name: Set up Python ${{ matrix.python-version }}
      uses: actions/setup-python@v4
      with:
        python-version: ${{ matrix.python-version }}

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt
        pip install coverage # Ensure coverage is installed

    - name: Run tests with coverage
      run: |
        coverage run -m unittest discover tests

    - name: Generate coverage report
      run: |
        coverage report -m
        # Optional: Upload coverage report artifact
        # coverage xml
        # - name: Upload coverage to Codecov
        #   uses: codecov/codecov-action@v3
        #   with:
        #     token: ${{ secrets.CODECOV_TOKEN }} # Optional: if using Codecov
        #     files: ./coverage.xml
        #     fail_ci_if_error: true